### ISSUE TITLE
Using Multer we are trying to uploade Image into the Backend and trying to fatch data from DB to Frontend 

### ISSUE THREAD

**Issue by CodeXtecch** [CodeXtecch/CodeXBlog#1]
Hear we have on Issue Related to Image using multer
File name Is : Create-blog-post.jsx and Edit-blog-post.jsx 

At the time of creation of we are storing image into backend using multer in server 
but at the time of fatching image from server this is not working so this is the proper issue to solve you 

![image](https://github.com/CodeXtecch/CodeXBlog/assets/159112376/c44a4ca4-4c8f-419c-9303-ec479fd82130)

**Comment by aryanpatel1503** [comment]
**in this issue i saw a code ther is a no issue in a multer but we are getting issues at the time of sending data into the server using api

Issue was the fromdata at the there is they   are passing data usnig append at that time   form data was not working with api so we make a one object and after that we convert that object into the json and than we save that into the backedend and all set it was working

in the image issue we convert image into base64 to store in a backend and after that fatch of image was working**
![image](https://github.com/CodeXtecch/CodeXBlog/assets/112875316/8b118539-b9c1-44d8-b371-fcf1aacee4c3)
